apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: name-based-virtualhost-ingress
spec:
  tls:
    - secretName: sqaaas-api-dev-secret 
    - secretName: sqaaas-api-stage-secret 
  rules:
  - host: api-dev.sqaaas.eosc-synergy.eu
    http:
      paths:
      - backend:
          serviceName: sqaaas-api-dev-service
          servicePort: 80
  - host: api-staging.sqaaas.eosc-synergy.eu
    http:
      paths:
      - backend:
          serviceName: sqaaas-api-stage-service
          servicePort: 80
